# PHP CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.1
    steps:
      - checkout
      - run: 
          name: Composer-normalize
          no_output_timeout: 20m
          command: composer normalize --dry-run
      - run: 
          name: PHP-Lint
          no_output_timeout: 20m
          command: parallel-lint --exclude vendor .
      - run: 
          name: Var-Dump-Check
          no_output_timeout: 20m
          command: var-dump-check .
      - run: 
          name: Merge-Conflict-Checker
          no_output_timeout: 20m
          command: merge_conflict_checker .
      - run: 
          name: Install-Check
          no_output_timeout: 20m
          command: composer install --no-interaction --prefer-source
  test-5.6:
    docker:
        - image: umutphp/php-docker-images-for-ci:5.6
    steps:
      - checkout
      - run: 
          name: Install-5-6
          no_output_timeout: 20m
          command: composer install --no-interaction --prefer-source
      - run:
          name: Unittest
          command: ./phpunit
  test-7.0:
    docker:
        - image: umutphp/php-docker-images-for-ci:7.0
    steps:
      - checkout
      - run:
          name: Install-7-0
          no_output_timeout: 20m
          command: composer install --no-interaction --prefer-source
      - run:
          name: Unittest
          command: ./phpunit
  test-7.1:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.1
    steps:
      - checkout
      - run:
          name: Install-7-1
          no_output_timeout: 20m
          command: composer install --no-interaction --prefer-source
      - run:
          name: Unittest
          command: ./phpunit
  test-7.2:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.2
    steps:
      - checkout
      - run:
          name: Install-7-2
          no_output_timeout: 20m
          command: composer install --no-interaction --prefer-source
      - run:
          name: Unittest
          command: ./phpunit
  test-7.3:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.3
    steps:
      - checkout
      - run:
          name: Install-7-3
          no_output_timeout: 20m
          command: composer install --no-interaction --prefer-source
      - run:
          name: Unittest
          command: ./phpunit
workflows:
  version: 2
  build_and_create:
    jobs:
      - build
      - test-5.6:
          requires:
            - build
      - test-7.0:
          requires:
            - build
      - test-7.1:
          requires:
            - build
      - test-7.2:
          requires:
            - build
      - test-7.3:
          requires:
            - build
